### ISSUE TITLE
Add Maybe

### ISSUE THREAD

**Issue by doomchild** [highbar/highbar-dotnet#3]
`Maybe` is a box that is either a `Just` of a value (of any type), or a `Nothing`.  It is technically a concrete implementation of the following categories:

1. Applicative
1. Alternative
1. Apply
1. Chain
1. Extend
1. Functor
1. Monad
1. Setoid

But I swear to God that anybody who tries to talk about it in those terms beyond this point should be fired into the sun.

**Comment by jlmorgan** [comment]
Not going to include `Alternative`? This would give you:

```
Maybe#empty
Maybe#alt
```

**Comment by doomchild** [comment]
I was just listing the categories you had ticked off on your node-fantasyland documentation, since I thought we were still mostly based off that stuff.  I already have `Maybe#empty` and `Maybe#alt` included.
